# Dependencies
markdown:         redcarpet
highlighter:      pygments
# This is the default format. 
permalink: pretty

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]


title : slowfish
tagline: ''
description:      '若你喜欢怪人，其实我很美'
author :
  name : slowfish
  email : thinkgarden1990@163.com
  github : thinkgarden1990

paginate:      5

comments :
    provider : duoshuo
    duoshuo :
          short_name : cellier-me

# The production_url is only used when full-domain names are needed
# such as sitemap.txt 
# Most places will/should use BASE_PATH to make the urls
#
# If you have set a CNAME (pages.github.com) set your custom domain here.
# Else if you are pushing to username.github.io, replace with your username.
# Finally if you are pushing to a GitHub project page, include the project name at the end.
#
#production_url : http://username.github.io

