# Setup
title:            慢鱼
email:          thinkgarden1990@163.com
description:      简简单单，随遇而安
url:              http://thinkgarden.github.io

production_url : http://thinkgarden.github.io

archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
atom_path : /atom.xml
rss_path : /rss.xml
github_username:  thinkgarden
# Outputting
permalink: pretty
# Build settings
markdown:  kramdown

paginate: 8
paginate_path: "page:num"

#highlight
highlighter: rouge
